name:                advent
version:             0.1.0.0
github:              "agentultra/advent"
license:             BSD3
author:              "James King"
maintainer:          "james@agentultra.com"
copyright:           "2020 James King"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/agentultra/advent#readme>

dependencies:
- base-noprelude >= 4.12 && < 5

default-extensions:
- GADTs
- LambdaCase
- OverloadedStrings
- RecordWildCards
- StandaloneDeriving
- TypeApplications

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - bytestring
  - containers
  - errors
  - relude
  - split
  - text
  - unordered-containers
  - vector

executables:
  advent2020:
    main:                Main.hs
    source-dirs:         app/Y2020/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -main-is Y2020.Main
    dependencies:
    - advent
  advent2021:
    main:                Main.hs
    source-dirs:         app/Y2021/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -main-is Y2021.Main
    dependencies:
    - advent

tests:
  advent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
    - unordered-containers
    - attoparsec
    - containers
    - hspec
    - text
    - vector
